### ISSUE TITLE
Fix histograms for other species

### ISSUE THREAD

**Issue by johnlees** [bacpop/BacQuerya#49]
Everything is based on the pneumo data at the moment. We could either hide, or change so it's recomputed for other species

**Comment by Danderson123** [comment]
Assembly statistic visualisations are species-specific for S. pneumoniae and E. coli, specified by this GET request https://github.com/bacpop/BacQuerya/blob/7ab931f51999b846b69cffb34f7e259c394d7e26/src/components/indexQuerying/isolateQuery.js#L24

**Comment by johnlees** [comment]
I thought that I'd seen one where this was wrong (seeing an E. coli length of 4Mb with the S.pneumoniae mean around 2Mb), but looking now seems fine. Maybe I had a cached version or something
